/* Copyright 2026 Lalf/GroupTRON */
/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define SPI_SCK_PIN							GP22
#define SPI_MOSI_PIN						GP23
#define SPI_MISO_PIN						GP20
#define PMW33XX_CS_PIN						GP21

#define PMW33XX_CPI							1000
#define PMW33XX_CLOCK_SPEED					2000000
#define PMW33XX_LIFTOFF_DISTANCE			3
#define MOUSE_EXTENDED_REPORT

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET

/* wear leveling */
#define PICO_FLASH_SIZE_BYTES				(16 * 1024 * 1024)
#define WEAR_LEVELING_BACKING_SIZE			131072
#define WEAR_LEVELING_LOGICAL_SIZE			(WEAR_LEVELING_BACKING_SIZE / 2)
#define WEAR_LEVELING_RP2040_FLASH_SIZE		(PICO_FLASH_SIZE_BYTES)
#define WEAR_LEVELING_RP2040_FLASH_BASE		((WEAR_LEVELING_RP2040_FLASH_SIZE) - (WEAR_LEVELING_BACKING_SIZE))
#define BACKING_STORE_WRITE_SIZE			2
